-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 15:39:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema veganerlandDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veganerlandDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veganerlandDb` DEFAULT CHARACTER SET utf8 ;
USE `veganerlandDb` ;

-- -----------------------------------------------------
-- Table `veganerlandDb`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerlandDb`.`CUSTOMER` (
  `CUSTID` INT NOT NULL,
  `FIRSTNAME` VARCHAR(45) NOT NULL,
  `LASTNAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `PHONE` VARCHAR(20) NULL,
  `PASSWORD` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ubdatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`CUSTID`));


-- -----------------------------------------------------
-- Table `veganerlandDb`.`ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerlandDb`.`ORDERS` (
  `ORDID` INT NOT NULL,
  `ORDERDATE` DATETIME NOT NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `CUSTID` INT NOT NULL,
  `SHIPDATE` DATETIME NULL,
  PRIMARY KEY (`ORDID`),
  UNIQUE INDEX `CUSTID_UNIQUE` (`CUSTID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `veganerlandDb`.`ADRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerlandDb`.`ADRESS` (
  `ADRESSID` INT NOT NULL,
  `STREET` VARCHAR(50) NOT NULL,
  `HouseNumber` INT NOT NULL,
  `PLZ` VARCHAR(5) NOT NULL,
  `CITY` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ADRESSID`));


-- -----------------------------------------------------
-- Table `veganerlandDb`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerlandDb`.`PRODUCTS` (
  `PRODID` INT NOT NULL,
  `DESCRIP` VARCHAR(50) NOT NULL,
  `CAT` VARCHAR(30) NOT NULL,
  `STDPRICE` DECIMAL(7,2) NOT NULL,
  `PRODUCTScol` VARCHAR(45) NULL,
  PRIMARY KEY (`PRODID`));


-- -----------------------------------------------------
-- Table `veganerlandDb`.`ORDERITEMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerlandDb`.`ORDERITEMS` (
  `ORDID` INT NOT NULL,
  `ITEMID` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PRODID` INT NOT NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `ACTUALPRICE` DECIMAL(8,2) NOT NULL,
  `QTY` INT NOT NULL,
  PRIMARY KEY (`ITEMID`, `ORDID`),
  UNIQUE INDEX `PRODID_UNIQUE` (`PRODID` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
