-- MySQL Script generated by MySQL Workbench
-- Mon Dec 28 15:33:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema veganerLand
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veganerLand
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veganerLand` DEFAULT CHARACTER SET utf8 ;
USE `veganerLand` ;

-- -----------------------------------------------------
-- Table `veganerLand`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`products` (
  `prodId` INT NOT NULL AUTO_INCREMENT,
  `descrip` VARCHAR(50) NOT NULL,
  `cat` CHAR(1) NOT NULL,
  `stdPrice` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`prodId`),
  UNIQUE INDEX `PRODID_UNIQUE` (`prodId` ASC));


-- -----------------------------------------------------
-- Table `veganerLand`.`orderitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`orderitems` (
  `itemId` INT NOT NULL AUTO_INCREMENT,
  `prodId` INT NOT NULL,
  `qyt` INT NOT NULL,
  PRIMARY KEY (`itemId`),
  UNIQUE INDEX `ITEMID_UNIQUE` (`itemId` ASC),
  INDEX `fk_ORDERITEMS_PRODUCTS_idx` (`prodId` ASC),
  CONSTRAINT `fk_ORDERITEMS_PRODUCTS`
    FOREIGN KEY (`prodId`)
    REFERENCES `veganerLand`.`products` (`prodId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `veganerLand`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`address` (
  `addressId` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `zip` VARCHAR(5) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`addressId`));


-- -----------------------------------------------------
-- Table `veganerLand`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`customers` (
  `custId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `tocken` VARCHAR(50) NULL,
  `phone` VARCHAR(20) NULL,
  `gender` VARCHAR(1) NULL,
  `password` VARCHAR(50) NOT NULL,
  `addressId` INT NULL,
  PRIMARY KEY (`custId`),
  UNIQUE INDEX `CUSTID_UNIQUE` (`custId` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`email` ASC),
  INDEX `fk_CUSTOMER_address1_idx` (`addressId` ASC),
  CONSTRAINT `fk_CUSTOMER_address1`
    FOREIGN KEY (`addressId`)
    REFERENCES `veganerLand`.`address` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `veganerLand`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`orders` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `itemId` INT NOT NULL,
  `custId` INT NOT NULL,
  `orderDate` timestamp NOT NULL DEFAULT CURRENT_timestamp,
  `shipDate` timestamp NULL,
  `addressId` INT NOT NULL,
  PRIMARY KEY (`orderId`),
  UNIQUE INDEX `ORDERID_UNIQUE` (`orderId` ASC),
  INDEX `fk_ORDERS_ORDERITEMS1_idx` (`itemId` ASC),
  INDEX `fk_ORDERS_CUSTOMER1_idx` (`custId` ASC),
  INDEX `fk_ORDERS_address1_idx` (`addressId` ASC),
  CONSTRAINT `fk_ORDERS_ORDERITEMS1`
    FOREIGN KEY (`itemId`)
    REFERENCES `veganerLand`.`orderitems` (`itemId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDERS_CUSTOMER1`
    FOREIGN KEY (`custId`)
    REFERENCES `veganerLand`.`customers` (`custId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDERS_address1`
    FOREIGN KEY (`addressId`)
    REFERENCES `veganerLand`.`address` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `veganerLand`.`favorits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`favorits` (
  `prodId` INT NOT NULL,
  `custId` INT NOT NULL,
  INDEX `fk_favoriten_products1_idx` (`prodId` ASC),
  INDEX `fk_favorits_customers1_idx` (`custId` ASC),
  CONSTRAINT `fk_favoriten_products1`
    FOREIGN KEY (`prodId`)
    REFERENCES `veganerLand`.`products` (`prodId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorits_customers1`
    FOREIGN KEY (`custId`)
    REFERENCES `veganerLand`.`customers` (`custId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

--
-- Daten für Tabelle `products`
--

INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES
(1, 'karotten', 'V', '1.94'),
(2, 'kartoffeln', 'V', '2.94'),
(3, 'lauchzwiebel', 'V', '0.94'),
(4, 'trauben-hell', 'F', '1.64'),
(5, 'heidelbeeren', 'F', '1.95'),
(6, 'avocado', 'F', '0.94'),
(7, 'orangen', 'F', '2.00'),
(8, 'clementine', 'F', '1.64'),
(9, 'mango', 'F', '1.94'),
(10, 'apfel-grün', 'F', '1.34'),
(11, 'kaki', 'F', '0.94'),
(12, 'aprikosen', 'F', '0.89'),
(13, 'himbeere', 'F', '2.94'),
(14, 'ananas', 'F', '1.94'),
(15, 'wassermelone', 'F', '0.94'),
(16, 'apfel-rot', 'F', '1.54'),
(19, 'banana', 'F', '0.76'),
(20, 'birne', 'F', '1.45'),
(21, 'aubergine', 'V', '2.47'),
(22, 'blumenkohl', 'V', '1.36'),
(23, 'erdbeeren', 'F', '4.80'),
(24, 'granatapfel', 'F', '2.35'),
(25, 'broccoli', 'V', '1.36'),
(26, 'champignons', 'V', '4.37'),
(27, 'grapefruit', 'F', '6.75'),
(28, 'kirschen', 'F', '2.45'),
(29, 'kiwi', 'F', '1.43'),
(30, 'trauben-dunkel', 'F', '1.96'),
(31, 'fenchel', 'V', '1.47'),
(32, 'gurke', 'V', '0.76'),
(33, 'ingwer', 'V', '2.76'),
(34, 'knoblauch', 'V', '0.83'),
(35, 'kohlrabi', 'V', '2.13'),
(36, 'paprika', 'V', '2.43'),
(37, 'porree', 'V', '1.75'),
(38, 'radieschen', 'V', '1.25'),
(39, 'salat', 'V', '4.32'),
(40, 'süsskartoffeln', 'V', '3.76'),
(41, 'tomaten', 'V', '1.20'),
(42, 'zucchini', 'V', '0.56'),
(43, 'zwiebeln', 'V', '6.73');
