-- MySQL Script generated by MySQL Workbench
-- Fri Dec 11 11:26:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema veganerLand
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veganerLand
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veganerLand` DEFAULT CHARACTER SET utf8 ;
USE `veganerLand` ;

-- -----------------------------------------------------
-- Table `veganerLand`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`products` (
  `PRODID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIP` VARCHAR(50) NOT NULL,
  `CAT` CHAR(1) NOT NULL,
  `STDPRICE` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`PRODID`),
  UNIQUE INDEX `PRODID_UNIQUE` (`PRODID` ASC));


-- -----------------------------------------------------
-- Table `veganerLand`.`orderitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`orderitems` (
  `ITEMID` INT NOT NULL AUTO_INCREMENT,
  `PRODID` INT NOT NULL,
  `QYT` INT NOT NULL,
  PRIMARY KEY (`ITEMID`),
  UNIQUE INDEX `ITEMID_UNIQUE` (`ITEMID` ASC) ,
  INDEX `fk_ORDERITEMS_PRODUCTS_idx` (`PRODID` ASC) ,
  CONSTRAINT `fk_ORDERITEMS_PRODUCTS`
    FOREIGN KEY (`PRODID`)
    REFERENCES `veganerLand`.`products` (`PRODID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `veganerLand`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`address` (
  `addressId` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `zip` VARCHAR(5) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`addressId`));


-- -----------------------------------------------------
-- Table `veganerLand`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`customers` (
  `custId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `LASTNAME` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `gender` VARCHAR(1) NULL,
  `password` VARCHAR(50) NOT NULL,
  `addressId` INT NULL,
  PRIMARY KEY (`custId`),
  UNIQUE INDEX `custId_UNIQUE` (`custId` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_CUSTOMER_address1_idx` (`addressId` ASC),
  CONSTRAINT `fk_CUSTOMER_address1`
    FOREIGN KEY (`addressId`)
    REFERENCES `veganerLand`.`address` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `veganerLand`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`orders` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `itemId` INT NOT NULL,
  `custId` INT NOT NULL,
  `orderDate` timestamp NOT NULL DEFAULT CURRENT_timestamp,
  `shipDate` timestamp NULL,
  `addressId` INT NOT NULL,
  PRIMARY KEY (`orderId`),
  UNIQUE INDEX `ORDERID_UNIQUE` (`orderId` ASC),
  INDEX `fk_ORDERS_ORDERITEMS1_idx` (`itemId` ASC),
  INDEX `fk_ORDERS_CUSTOMER1_idx` (`custId` ASC),
  INDEX `fk_ORDERS_address1_idx` (`addressId` ASC),
  CONSTRAINT `fk_ORDERS_ORDERITEMS1`
    FOREIGN KEY (`itemId`)
    REFERENCES `veganerLand`.`orderitems` (`ITEMID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDERS_CUSTOMER1`
    FOREIGN KEY (`custId`)
    REFERENCES `veganerLand`.`customers` (`CUSTID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDERS_address1`
    FOREIGN KEY (`addressId`)
    REFERENCES `veganerLand`.`address` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
