-- MySQL Script generated by MySQL Workbench
-- Fri Dec 18 17:13:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema veganerLand
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veganerLand
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veganerLand` DEFAULT CHARACTER SET utf8 ;
USE `veganerLand` ;

-- -----------------------------------------------------
-- Table `veganerLand`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`products` (
  `prodId` INT NOT NULL AUTO_INCREMENT,
  `descrip` VARCHAR(50) NOT NULL,
  `cat` CHAR(1) NOT NULL,
  `stdPrice` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`prodId`),
  UNIQUE INDEX `PRODID_UNIQUE` (`prodId` ASC));


-- -----------------------------------------------------
-- Table `veganerLand`.`orderitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`orderitems` (
  `itemId` INT NOT NULL AUTO_INCREMENT,
  `prodId` INT NOT NULL,
  `qyt` INT NOT NULL,
  PRIMARY KEY (`itemId`),
  UNIQUE INDEX `ITEMID_UNIQUE` (`itemId` ASC),
  INDEX `fk_ORDERITEMS_PRODUCTS_idx` (`prodId` ASC),
  CONSTRAINT `fk_ORDERITEMS_PRODUCTS`
    FOREIGN KEY (`prodId`)
    REFERENCES `veganerLand`.`products` (`prodId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `veganerLand`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`address` (
  `addressId` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `zip` VARCHAR(5) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`addressId`));


-- -----------------------------------------------------
-- Table `veganerLand`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`customers` (
  `custId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `gender` VARCHAR(1) NULL,
  `password` VARCHAR(50) NOT NULL,
  `addressId` INT NULL,
  PRIMARY KEY (`custId`),
  UNIQUE INDEX `CUSTID_UNIQUE` (`custId` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`email` ASC),
  INDEX `fk_CUSTOMER_address1_idx` (`addressId` ASC),
  CONSTRAINT `fk_CUSTOMER_address1`
    FOREIGN KEY (`addressId`)
    REFERENCES `veganerLand`.`address` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `veganerLand`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`orders` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `itemId` INT NOT NULL,
  `custId` INT NOT NULL,
  `orderDate` DATETIME NOT NULL DEFAULT CURRENT_timestamp,
  `shipDate` timestamp NULL,
  `addressId` INT NOT NULL,
  PRIMARY KEY (`orderId`),
  UNIQUE INDEX `ORDERID_UNIQUE` (`orderId` ASC),
  INDEX `fk_ORDERS_ORDERITEMS1_idx` (`itemId` ASC),
  INDEX `fk_ORDERS_CUSTOMER1_idx` (`custId` ASC),
  INDEX `fk_ORDERS_address1_idx` (`addressId` ASC),
  CONSTRAINT `fk_ORDERS_ORDERITEMS1`
    FOREIGN KEY (`itemId`)
    REFERENCES `veganerLand`.`orderitems` (`itemId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDERS_CUSTOMER1`
    FOREIGN KEY (`custId`)
    REFERENCES `veganerLand`.`customers` (`custId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDERS_address1`
    FOREIGN KEY (`addressId`)
    REFERENCES `veganerLand`.`address` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `veganerLand`.`favorits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerLand`.`favorits` (
  `prodId` INT NOT NULL,
  `custId` INT NOT NULL,
  INDEX `fk_favoriten_products1_idx` (`prodId` ASC),
  INDEX `fk_favorits_customers1_idx` (`custId` ASC),
  CONSTRAINT `fk_favoriten_products1`
    FOREIGN KEY (`prodId`)
    REFERENCES `veganerLand`.`products` (`prodId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorits_customers1`
    FOREIGN KEY (`custId`)
    REFERENCES `veganerLand`.`customers` (`custId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
               
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Speisemöhren', 'V', '1.94');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Speisekartoffeln', 'V', '2.94');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Weißer Spargel', 'V', '0.94');

INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Helle Tafeltrauben', 'F', '1.64');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Heidelbeeren', 'F', '1.95');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Vorgereifte Avocado', 'F', '0.94');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Orangen', 'F', '2.00');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Clementinen', 'F', '1.64');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Mango essreif', 'F', '1.94');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Apfel Braeburn rot', 'F', '1.34');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Kaki', 'F', '0.94');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Avocado', 'F', '1.94');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Himbeere', 'F', '2.94');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Mandarine Bio', 'F', '1.94');
INSERT INTO `products` (`prodId`, `descrip`, `cat`, `stdPrice`) VALUES (NULL, 'Galiamelone', 'F', '0.94');
