-- MySQL Script generated by MySQL Workbench
-- Sun Jan 24 10:47:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema veganerland
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veganerland
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `veganerland` DEFAULT CHARACTER SET utf8 ;
USE `veganerland` ;

-- -----------------------------------------------------
-- Table `veganerland`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerland`.`category` (
  `catId` INT NOT NULL AUTO_INCREMENT,
  `descrip` VARCHAR(30) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`catId`));


-- -----------------------------------------------------
-- Table `veganerland`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerland`.`products` (
  `prodId` INT NOT NULL AUTO_INCREMENT,
  `descrip` VARCHAR(50) NOT NULL,
  `stdPrice` DECIMAL(5,2) NOT NULL,
  `catId` INT NOT NULL,
  `comment` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`prodId`),
  UNIQUE INDEX `PRODID_UNIQUE` (`prodId` ASC),
  INDEX `fk_products_category1_idx` (`catId` ASC),
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`catId`)
    REFERENCES `veganerland`.`category` (`catId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `veganerland`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerland`.`address` (
  `addressId` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `zip` VARCHAR(5) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`addressId`));


-- -----------------------------------------------------
-- Table `veganerland`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerland`.`customers` (
  `custId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `tocken` VARCHAR(50) NULL,
  `phone` VARCHAR(20) NULL,
  `gender` VARCHAR(1) NULL,
  `password` VARCHAR(50) NOT NULL,
  `addressId` INT NULL,
  PRIMARY KEY (`custId`),
  UNIQUE INDEX `CUSTID_UNIQUE` (`custId` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`email` ASC),
  INDEX `fk_CUSTOMER_address1_idx` (`addressId` ASC),
  CONSTRAINT `fk_CUSTOMER_address1`
    FOREIGN KEY (`addressId`)
    REFERENCES `veganerland`.`address` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `veganerland`.`orderitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerland`.`orderitems` (
  `itemId` INT NOT NULL AUTO_INCREMENT,
  `custId` INT NOT NULL,
  `prodId` INT NOT NULL,
  `qyt` INT NOT NULL,
  `isSend` ENUM('f', 't') NOT NULL DEFAULT 'f',
  PRIMARY KEY (`itemId`),
  UNIQUE INDEX `ITEMID_UNIQUE` (`itemId` ASC),
  INDEX `fk_ORDERITEMS_PRODUCTS_idx` (`prodId` ASC),
  INDEX `fk_orderitems_customers1_idx` (`custId` ASC),
  CONSTRAINT `fk_ORDERITEMS_PRODUCTS`
    FOREIGN KEY (`prodId`)
    REFERENCES `veganerland`.`products` (`prodId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderitems_customers1`
    FOREIGN KEY (`custId`)
    REFERENCES `veganerland`.`customers` (`custId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `veganerland`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerland`.`orders` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `itemId` INT NOT NULL,
  `orderDate` DATETIME NOT NULL DEFAULT current_timestamp(),
  `shipDate` DATETIME NULL,
  `addressId` INT NOT NULL,
  PRIMARY KEY (`orderId`),
  UNIQUE INDEX `ORDERID_UNIQUE` (`orderId` ASC),
  INDEX `fk_ORDERS_ORDERITEMS1_idx` (`itemId` ASC),
  INDEX `fk_ORDERS_address1_idx` (`addressId` ASC),
  CONSTRAINT `fk_ORDERS_ORDERITEMS1`
    FOREIGN KEY (`itemId`)
    REFERENCES `veganerland`.`orderitems` (`itemId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDERS_address1`
    FOREIGN KEY (`addressId`)
    REFERENCES `veganerland`.`address` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `veganerland`.`favorits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veganerland`.`favorits` (
  `prodId` INT NOT NULL,
  `custId` INT NOT NULL,
  INDEX `fk_favoriten_products1_idx` (`prodId` ASC),
  INDEX `fk_favorits_customers1_idx` (`custId` ASC),
  CONSTRAINT `fk_favoriten_products1`
    FOREIGN KEY (`prodId`)
    REFERENCES `veganerland`.`products` (`prodId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorits_customers1`
    FOREIGN KEY (`custId`)
    REFERENCES `veganerland`.`customers` (`custId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
               
INSERT INTO `address` (`addressId`, `street`, `number`, `zip`, `city`) 
VALUES (1, 'Döllstädtstraße', '8', '99423', 'Weimar');

INSERT INTO `customers` (`custId`, `firstName`, `lastName`, `email`, `tocken`, `phone`, `gender`, `password`, `addressId`) 
VALUES (NULL, 'Max', 'Mustermann', 'mustermann@gmail.de', NULL, '015721154196', 'm', '256dfa07820d7d34acbe3a41744b8e09', '1');

INSERT INTO `category` (`catId`, `descrip`, `name`) VALUES
(NULL, 'fruits', 'alle'),
(NULL, 'fruits_berry', 'beeren'),
(NULL, 'fruits_citrus', 'zitrusfrüchte'),
(NULL, 'fruits_exotics', 'exoten'),
(NULL, 'fruits_nuts', 'nüsse'),
(NULL, 'vegetables', 'alle'),
(NULL, 'vegetables_potato', 'kartoffeln'),
(NULL, 'vegetables_mushroom', 'pilze');

INSERT INTO `products` (`prodId`, `descrip`, `stdPrice`, `catId`, `comment`) VALUES
(NULL, 'karotten', '1.95', 6, 'Bio,_Regional,_500g'),
(NULL, 'kartoffeln°', '3.15', 7, 'Bio,_Regional,_1kg,_°festkochend'),
(NULL, 'shiitake', '2.95', 8, 'Bio,_100g'),
(NULL, 'zwiebeln', '1.95', 6, 'Bio,_Regional,_500g'),
(NULL, 'ingwer', '1.20', 6, 'Bio,_100g'),
(NULL, 'paprika_(rot)', '5.40', 6, '3_Stück'),
(NULL, 'knoblauch', '1.95', 6, 'Bio,_100g'),
(NULL, 'kräuterseitlinge', '6.95', 8, 'Bio,_Regional,_250g'),
(NULL, 'zwiebeln_(rot)', '2.40', 6, 'Bio,_500g'),
(NULL, 'kartoffeln_(mehlig)', '7.50', 7, 'Bio,_Regional,_2,5kg'),
(NULL, 'igelstachelbart-pilze', '6.95', 8, 'Bio,_250g'),
(NULL, 'spinat', '4.50', 6, 'Bio,_Regional,_500g'),
(NULL, 'landgurke', '1.95', 6, 'Bio,_Regional,_1_Stück'),
(NULL, 'landgurke', '1.55', 6, 'Regional,_1_Stück'),
(NULL, 'kohlrabi', '2.15', 6, 'Bio,_1_Stück'),
(NULL, 'blumenkohl', '4.50', 6, '1_Stück'),
(NULL, 'brokkoli', '3.95', 6, '500g'),
(NULL, 'radieschen', '1.50', 6, 'Bio,_100g'),
(NULL, 'kartoffeln°°', '3.25', 7, 'Bio,_1kg,_°°vorwiegend_festkochend'),
(NULL, 'süsskartoffeln', '2.50', 7, 'Bio,_500g'),
(NULL, 'kartoffeln_(rund)', '3.75', 7, '1kg'),
(NULL, 'kartoffeln_(blau)', '4.00', 7, 'Bio,_1kg'),
(NULL, 'judasohr', '6.95', 8, 'Bio,_250g'),
(NULL, 'pfifferlinge', '5.55', 8, 'Bio,_Regional,_250g'),
(NULL, 'steinpilze', '4.55', 8, 'Regional,_250g'),
(NULL, 'champignons_(klasse_a)', '4.55', 8, 'Regional,_250g'),
(NULL, 'tomaten', '3.95', 6, 'Bio,_500g'),
(NULL, 'paprika_(gelb)', '5.40', 6, '3_Stück'),
(NULL, 'paprika_(grün)', '5.40', 6, '3_Stück'),
(NULL, 'paprika_(mix)', '5.40', 6, '3_Stück'),
(NULL, 'äpfel_(grün)', '6.50', 1, 'Bio,_Regional,__1kg'),
(NULL, 'äpfel_(grün)', '3.50', 1, 'Bio,_Regional,_500g'),
(NULL, 'äpfel_(grün)', '0.75', 1, 'Bio,_Regional,_1_Stück'),
(NULL, 'äpfel_(rot)', '6.50', 1, 'Bio,_Regional,_1kg'),
(NULL, 'äpfel_(rot)', '3.50', 1, 'Bio,_Regional,_500g'),
(NULL, 'äpfel_(rot)', '0.75', 1, 'Bio,_Regional,_1_Stück'),
(NULL, 'orangen', '1.75', 3, 'Bio,_500g'),
(NULL, 'bananen', '1.80', 4, 'Bio,_500g'),
(NULL, 'bananen', '1.40', 4, '500g'),
(NULL, 'birnen', '5.50', 1, 'Regional,_1kg'),
(NULL, 'ananas', '3.75', 4, 'Bio,_1_Stück'),
(NULL, 'mango', '2.25', 4, 'Bio,_1_Stück'),
(NULL, 'kiwi', '2.90', 4, 'Bio,_500g'),
(NULL, 'granatapfel', '2.35', 4, 'Bio,_1_Stück'),
(NULL, 'zitronen', '2.00', 3, 'Bio,_500g'),
(NULL, 'clementinen', '2.50', 3, '500g'),
(NULL, 'grapefruit', '1.75', 3, 'Bio,_1_Stück'),
(NULL, 'avocado', '2.45', 4, 'Bio,_1_Stück'),
(NULL, 'erdnüsse', '1.95', 5, 'Bio,_150g'),
(NULL, 'edelkastanie', '3.50', 5, '250g'),
(NULL, 'heidelbeeren', '1.95', 2, 'Bio,_Regional,_150g'),
(NULL, 'himbeere', '1.75', 2, 'Bio,_Regional,_150g'),
(NULL, 'brombeere', '1.75', 2, 'Bio,_Regional,_150g'),
(NULL, 'erdbeere', '1.25', 2, 'Bio,_Regional,_150g'),
(NULL, 'erdbeere', '1.95', 2, 'Bio,_Regional,_300g'),
(NULL, 'johannisbeeren_(rot)', '2.20', 2, 'Bio,_150g'),
(NULL, 'beeren-mix', '2.50', 2, '250g'),
(NULL, 'limetten', '1.20', 3, 'Bio,_250g'),
(NULL, 'mandarinen', '1.25', 3, 'Bio,_250g'),
(NULL, 'walnuss', '2.25', 5, 'Regional,_250g'),
(NULL, 'haselnuss', '3.50', 5, '250g'),
(NULL, 'macadamia', '3.75', 5, '250g'),
(NULL, 'pistazie', '2.50', 5, 'Bio,_250g'),
(NULL, 'weintraube_(hell)', '1.64', 1, 'Bio,_150g'),
(NULL, 'weintraube_(dunkel)', '1.64', 1, 'Bio,_150g'),
(NULL, 'kirschen', '2.45', 1, 'Bio,_Regional,_250g'),
(NULL, 'wassermelone', '0.94', 1, '1_Stück');


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
